### ISSUE TITLE
Plugin keeps crashing Sketch 51.2

### ISSUE THREAD

**Issue by JIGZ26** [atlassian/jira-cloud-for-sketch#14] opened 2018-08-31 10:02 UTC
Every time I load the Jira plugin in Sketch, give it 5 seconds then the plugin closes Sketch down and then Sketch is opened in safe mode.

This happens every time without fail.

The plugin is unusable for our design to use as part of a workflow.

**Comment by kannonboy** [comment] 2018-09-20 03:47
Hi @JIGZ26, thanks for the report! I haven't managed to reproduce this in my local version of Sketch 51.2.

So I can determine what's causing the error, would you mind sending me your plugin log file? It is cleared automatically whenever Sketch is restarted, so you'll need to:

1. Reproduce the crash.
2. Send me the file at ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log

An easy way to get to this file is by opening Console.app (under Applications -> Utilities), navigating to "Plugin Output.log", right-clicking and clicking "Reveal in Finder".

Depending on the plugins you're using, the log may contain sensitive details, so best to take a quick look through it first and/or email it to tim@atlassian.com rather than attaching it to this issue.

Thanks for your help!

**Comment by aembe** [comment] 2018-10-08 13:11
has there been any progress on this issue?
Having the same problem here

**Comment by JIGZ26** [comment] 2018-10-08 13:12
Still having the issue, I have stopped using this plugin due to the problems it is causing.

**Comment by SamanthaHaskell** [comment] 2018-10-09 19:48
I am also having this issue. Please address.

**Comment by kannonboy** [comment] 2018-10-11 00:53
Hi folks,

Sorry for the delay. We've reproduced the issue internally but unfortunately there isn't a straightforward fix. Something deep within the Sketch plugin system changed in version 51 that means the way that we update the floating Jira panel when your layer selection changes causes Sketch to crash (at https://github.com/atlassian/jira-cloud-for-sketch/blob/master/src/plugin-state.js#L73 specifically). 

We're continuing to investigate solutions for the problem, but we may need to do some significant reworking of the plugin UX to workaround this issue, which will take some design and engineering time. Please bear with us :)

cheers,
Tim

**Comment by Naxit** [comment] 2018-10-14 19:51
Hi everyone,
Same issue here, waiting for the patch. Keep digging guys !

**Comment by tillyguess** [comment] 2018-10-30 13:52
Is there any update on when this will be fixed?

**Comment by kannonboy** [comment] 2018-11-01 03:11
Good news everyone!

We released Jira Cloud for Sketch v1.1.3 today, which fixes the crashing bug. You can [download it here](https://s3-us-west-2.amazonaws.com/atlassian-sketch-plugin/jira.sketchplugin-1.1.3.zip), or follow the "Plugin Updates Available" prompt within Sketch if you still have an earlier version installed.

Note: There remains a regression under Sketch 52+ where the Jira button no longer appears on the export panel due to some changes in the Sketch UI layout. However, you can still open the Jira panel via the Plugins menu, or by pressing ⌥⌘J

Thanks for your patience folks!

**Closed as completed** 2018-11-01 03:11 UTC
